In [1]:
import torch
import torch.nn as nn


import numpy as np
import pandas as pd

### Dataset loading and exploration

In [7]:
dataset = pd.read_csv("data\\news_500.csv")
dataset

,Unnamed: 0,id,fronturl,publish_date_t,publish_date,title,photo,project,category,opinion_authors,authors,anons,overview,text
0,0,5703b1e99a7947783a5a159a,http://www.rbc.ru/economics/28/09/2000/5703b1e...,970130997,"Thu, 28 Sep 2000 12:49:57 +0400",В.Путин торопит разработчиков военной реформы,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... заявление он сделал перед совещанием чле...,"Президент России Владимир Путин считает, что к...","Президент России Владимир Путин считает, что к..."
1,1,5703b1ea9a7947783a5a15b3,http://www.rbc.ru/economics/04/10/2000/5703b1e...,970648343,"Wed, 04 Oct 2000 12:32:23 +0400",Арафат и Барак будут договариваться,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... всеобъемлющего урегулирования по всем гл...,Глава Палестинской автономии Ясир Арафат напра...,Перед отъездом Я.Арафат провел совещание с пре...
2,2,5703b1e99a7947783a5a15a0,http://www.rbc.ru/economics/03/10/2000/5703b1e...,970581338,"Tue, 03 Oct 2000 17:55:38 +0400",Седьмая годовщина пролетарской революции,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... и манифестаций. Совместными колоннами пр...,Сегодня Москва отмечает 7-ую годовщину трагиче...,В связи с этим власти дали разрешение на прове...
3,3,5703b1e99a7947783a5a15a6,http://www.rbc.ru/economics/03/10/2000/5703b1e...,970570495,"Tue, 03 Oct 2000 14:54:55 +0400","Вяхирев хочет продать ""Медиа-Мост"" европейцам",{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,"... при прекращении дефолта, что ""Медиа-Мост...",Сопровождающий президента России Владимира Пут...,"По словам Р.Вяхирева, это будет открытый тенде..."
4,4,5703b1ee9a7947783a5a15dc,http://www.rbc.ru/economics/12/10/2000/5703b1e...,971360547,"Thu, 12 Oct 2000 18:22:27 +0400",Китай наконец удостоен Нобеля,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... области литературы за «проницательность ...,"Китайский новеллист Гао Синьхуан, проживающий ...","Литературная премия, обладатель которой обычно..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,495,5703be6b9a7947afa08cc9e9,http://www.rbc.ru/economics/13/11/2001/5703be6...,1005598861,"Tue, 13 Nov 2001 00:01:01 +0300",«Столичной» водки станет больше. Нужно подожда...,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... сообщил генеральный директор ЗАО «Союзпл...,ЗАО «Союзплодимпорт» планирует превысить объем...,Как сообщил генеральный директор ЗАО «Союзплод...
496,496,5703b47b9a7947783a5a397e,http://www.rbc.ru/economics/13/11/2001/5703b47...,1005598861,"Tue, 13 Nov 2001 00:01:01 +0300",«Столичной» водки станет больше. Нужно подожда...,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... сообщил генеральный директор ЗАО «Союзпл...,ЗАО «Союзплодимпорт» планирует превысить объем...,Как сообщил генеральный директор ЗАО «Союзплод...
497,497,5703b47b9a7947783a5a3978,http://www.rbc.ru/economics/12/11/2001/5703b47...,1005549071,"Mon, 12 Nov 2001 10:11:11 +0300",Российские законы усовершенствуют для вступлен...,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,"... , посвященные перспективам вступления Рос...",Комитет Госдумы РФ по экономической политике и...,Как заявил РБК председатель Общественного сове...
498,498,5703be6a9a7947afa08cc9df,http://www.rbc.ru/economics/12/11/2001/5703be6...,1005549071,"Mon, 12 Nov 2001 10:11:11 +0300",Российские законы усовершенствуют для вступлен...,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,"... , посвященные перспективам вступления Рос...",Комитет Госдумы РФ по экономической политике и...,Как заявил РБК председатель Общественного сове...
499,499,5703be6a9a7947afa08cc9d2,http://www.rbc.ru/economics/11/11/2001/5703be6...,1005488298,"Sun, 11 Nov 2001 17:18:18 +0300",Депутаты Госдумы займутся офшорными банками,{'url': 'http://pics.v7.top.rbk.ru/v6_top_pics...,NaN,Экономика,NaN,NaN,... офшорных зон и центров международного би...,Государственная дума рассмотрит на пленарном з...,Об этом РБК сообщили в думском комитете по кре...

In [32]:
text_data = dataset[["text"]]
text_data

                                                  text
0    Президент России Владимир Путин считает, что к...
1    Перед отъездом Я.Арафат провел совещание с пре...
2    В связи с этим власти дали разрешение на прове...
3    По словам Р.Вяхирева, это будет открытый тенде...
4    Литературная премия, обладатель которой обычно...
..                                                 ...
495  Как сообщил генеральный директор ЗАО «Союзплод...
496  Как сообщил генеральный директор ЗАО «Союзплод...
497  Как заявил РБК председатель Общественного сове...
498  Как заявил РБК председатель Общественного сове...
499  Об этом РБК сообщили в думском комитете по кре...

[500 rows x 1 columns]

In [ ]:
def normalize(string: str) -> str:
    "Returns a normalized string"
    word_space_split = string.split()
    
    return word_space_split

' ...  заявление он сделал перед совещанием членов Совета безопасности РФ, сообщили <b>РБК</b> в администрации президента. . Президент России Владимир Путин считает, что концепция ... , забывая при этом, что сокращение тоже требует значительных средств, заявил <b>РБК</b> военный эксперт, говоря об итогах сегодняшнего рабочего совещания СБ. В ...  военнослужащих. "Так мы скоро можем вообще лишиться армии", - полагает собеседник <b>РБК</b>. По его мнению, сокращения численности армии (при сохранении уровня ее ... '